apiVersion: v1alpha1
kind: Setting
metadata:
  name: theme-butterfly-setting
spec:
  forms:
    - group: base
      label: 基本设置
      formSchema:
        - $formkit: text
          name: metadata_name
          label: 作者的唯一标识 metadata.name
          placeholder: 请填写 作者的唯一标识 metadata.name
          value: admin
          help: 后台用户管理中的用户名，不可乱填否则个人资料显示异常（示例：admin）
          validation: required
        - $formkit: text
          name: icp
          label: ICP 备案号
          placeholder: 请填写 ICP 备案号信息
          help: ICP 备案信息将展示在页脚中，不填不展示（示例：蜀ICP备xx号）
        - $formkit: text
          name: police
          label: 公网安备号
          placeholder: 请填写公网安备号信息
          help: 公网安备信息将展示在页脚中，不填不展示（示例：蜀公网安备xx号）
        - $formkit: text
          name: site_birthday
          label: 建站时间
          placeholder: 示例 2022-01-01 00:00
          help: 自定义博客的起始时间/安装时间，作为计算博客运行时间的参照值，请严格按照示例格式填写，否则将导致报错

    - group: style
      label: 主题设置
      formSchema:
        - $formkit: select
          name: theme_type
          label: 主题模式
          value: '#49b1f5'
          placeholder: 请填写主题颜色
          help: '设置博客的主题模式（用户/自动/浅色/暗黑），默认为用户模式，仅在用户模式下页面才有主题切换按钮，自动模式下根据时间自动切换'
          options:
            - value: user
              label: 用户模式
            - value: light
              label: 浅色模式
            - value: dark
              label: 暗黑模式
        - $formkit: text
          name: theme_color_light
          label: 主题颜色（浅白）
          value: '#49b1f5'
          placeholder: 请填写主题 浅白 颜色
          help: '主题颜色运用到大部分模块色调，默认 #49b1f5'
          validation: required
        - $formkit: text
          name: theme_color_dark
          label: 主题颜色（暗黑）
          value: '#ff7242'
          placeholder: 请填写主题 暗黑 颜色
          help: '主题颜色运用到大部分模块色调，默认 #ff7242'
          validation: required
        - $formkit: text
          name: content_max_width
          label: 内容区最大宽度
          value: 1250px
          placeholder: 请填写内容区最大宽度
          help: 内容区域最大宽度，像素或百分比，默认 1250px（注：文字布局为列表建议：1250px 平铺：1400px）
          validation: required
        - $formkit: attachment
          name: body_background
          label: 全局背景
          placeholder: 请填写 全局背景
          value: 'linear-gradient(90deg, rgba(247, 149, 51, .1) 0, rgba(243, 112, 85, .1) 15%, rgba(239, 78, 123, .1) 30%, rgba(161, 102, 171, .1) 44%, rgba(80, 115, 184, .1) 58%, rgba(16, 152, 173, .1) 72%, rgba(7, 179, 155, .1) 86%, rgba(109, 186, 130, .1) 100%)'
          help: 如果全局背景图设置为图片链接，第一屏背景图将不生效 (注：颜色值或图片链接) 默认：linear-gradient(90deg, rgba(247, 149, 51, .1) 0, rgba(243, 112, 85, .1) 15%, rgba(239, 78, 123, .1) 30%, rgba(161, 102, 171, .1) 44%, rgba(80, 115, 184, .1) 58%, rgba(16, 152, 173, .1) 72%, rgba(7, 179, 155, .1) 86%, rgba(109, 186, 130, .1) 100%)
          validation: required

    - group: loading
      label: 加载设置
      formSchema:
        - $formkit: attachment
          name: preload
          label: 预加载图片
          placeholder: 请填写 预加载图片
          value: 'data:image/gif;base64,R0lGODdhAQABAPAAAMPDwwAAACwAAAAAAQABAAACAkQBADs='
          help: 预加载图片，默认 data:image/gif;base64,R0lGODdhAQABAPAAAMPDwwAAACwAAAAAAQABAAACAkQBADs=
          validation: required
        - $formkit: attachment
          name: err
          label: 加载失败图片
          placeholder: 请填写 加载失败图片
          value: 'data:image/gif;base64,R0lGODdhAQABAPAAAMPDwwAAACwAAAAAAQABAAACAkQBADs='
          help: 加载失败图片，默认 data:image/gif;base64,R0lGODdhAQABAPAAAMPDwwAAACwAAAAAAQABAAACAkQBADs=
          validation: required
        - $formkit: attachment
          name: filter
          label: 预加载图片 css滤镜
          placeholder: 请填写 滤镜
          value: blur(50px) brightness(1)
          help: 滤镜，默认 blur(50px) brightness(1)
          validation: required

    - group: nav
      label: 导航设置
      formSchema:
        - $formkit: text
          name: font_color_light
          label: 导航字体颜色
          placeholder: 请填写 导航字体颜色
          value: '#eee'
          help: '导航字体颜色，默认 #eee'
          validation: required


    - group: card
      label: 卡片设置
      formSchema:
        - $formkit: text
          name: radius
          label: 卡片圆角
          placeholder: 请填写 卡片圆角
          value: 24px
          help: 卡片圆角，像素或百分比，默认 24px
          validation: required
        - $formkit: text
          name: bg_color
          label: 卡片背景色
          placeholder: 请填写 卡片背景色
          value: rgba(255, 255, 255, 0.6)
          help: 卡片背景色，颜色值，默认 rgba(255, 255, 255, 0.6)，透明值可选范围（0.1~1）1为不透明
          validation: required
        - $formkit: text
          name: shadow
          label: 卡片阴影
          placeholder: 请填写 卡片阴影
          value: 0 3px 8px 6px rgba(7,17,27,0.05)
          help: 卡片阴影，颜色值，默认 0 3px 8px 6px rgba(7,17,27,0.05)
          validation: required


    - group: aside
      label: 侧边栏设置
      formSchema:
        - $formkit: radio
          name: enable
          label: 启用侧边栏
          help: 是否启用侧边栏（全局），关闭后所有页面都没有侧边栏（优先级高于页面元数据）
          value: true
          options:
            - label: 启用
              value: true
            - label: 禁用
              value: false
        - $formkit: radio
          name: position
          label: 侧边栏位置
          help: 侧边栏展示位置，左边或右边
          value: aside-right
          options:
            - label: 左边
              value: aside-left
            - label: 右边
              value: aside-right
        - $formkit: textarea
          rows: 5
          name: button
          label: 侧边栏按钮
          placeholder: 请填写 侧边栏按钮内容
          value: 关注我&+&/
          help: 侧边栏按钮内容 (注：文案&+&链接 用&+&分割)
          validation: required
        - $formkit: textarea
          rows: 5
          name: notice
          label: 侧边栏公告
          placeholder: 请填写 侧边栏公告内容
          value: 好博客，一定要 分享出去 呀~
          help: 侧边栏公告内容, 支持 html 代码片段
        - $formkit: radio
          name: enable_category
          label: 启用侧边栏分类
          help: 是否启用侧边栏分类
          value: true
          options:
            - label: 启用
              value: true
            - label: 禁用
              value: false
        - $formkit: radio
          name: enable_tags
          label: 启用侧边栏标签
          help: 是否启用侧边栏标签
          value: true
          options:
            - label: 启用
              value: true
            - label: 禁用
              value: false
        - $formkit: radio
          name: enable_webInfo
          label: 启用侧边栏网站资讯
          help: 是否启用侧边栏网站资讯
          value: true
          options:
            - label: 启用
              value: true
            - label: 禁用
              value: false


    - group: index
      label: 首页设置
      formSchema:
        - $formkit: radio
          name: enable_above
          label: 启用第一屏
          help: 启用首页第一屏
          value: true
          options:
            - label: 启用
              value: true
            - label: 禁用
              value: false
        - $formkit: attachment
          name: above_background
          label: 第一屏背景图
          placeholder: 请填写 第一屏背景图
          value: 'https://dhjdd.cn/file/screenshot_1641478512166.jpg'
          help: 如果全局背景图设置为图片链接，则此处背景图将不生效
          validation: required
        - $formkit: textarea
          rows: 5
          name: typewriter
          label: 打字机文案
          placeholder: 请填写 打字机文案
          value: 欢迎来到我的博客 &+& 请填写打字机文案
          help: 首页第一屏打字机文案 (注：多个文案用 &+& 隔开)
          validation: required
        - $formkit: radio
          name: post_layout
          label: 文字布局方式
          help: 文章布局方式 提供（列表、平铺）两种，仅首页生效
          value: list
          options:
            - label: 列表
              value: list
            - label: 平铺
              value: tile

    # - group: post
    #   label: 文章设置
    #   formSchema: 
        

    - group: socials
      label: 社交设置
      formSchema:
        - $formkit: repeater
          name: no_data
          label: 社交账号
          help: 特殊跳转，请注意url中的参数值 如：QQ 只需要修改 uin= 后面的值即可，其他直接填写url即可，此处可直接填写html片段，svg图标代码片段
          value: 
            - name: QQ
              icon: <i class="fa-brands fa-qq"></i>
              url: tencent://AddContact/?fromId=50&amp;fromSubId=1&amp;subcmd=all&amp;uin=QQ号码
            - name: Github
              icon: <i class="fa-brands fa-github"></i>
              url:       
            - name: Email
              icon: <i class="fa-solid fa-envelope"></i>
              url: mailto:邮箱地址
        
          children:
            - $formkit: text
              name: name
              label: 名称
              value: ""
            - $formkit: text
              name: icon
              label: 图标
              value: ""
            - $formkit: textarea
              rows: 4
              name: url
              label: 地址
              value: ""
              
