apiVersion: 2.0
kind: Setting
metadata:
  name: theme-default-setting
spec:
  forms:
    - group: base
      label: 基本设置
      formSchema:
        - $formkit: text
          name: icp
          label: ICP 备案号
          placeholder: 请填写 ICP 备案号信息
          help: ICP 备案信息将展示在页脚中，不填不展示（示例：蜀ICP备xx号）
        - $formkit: text
          name: police
          label: 公网安备号
          placeholder: 请填写公网安备号信息
          help: 公网安备信息将展示在页脚中，不填不展示（示例：蜀公网安备xx号）
        - $formkit: text
          name: site_birthday
          label: 建站时间
          placeholder: 示例 2022-01-01
          help: 自定义博客的起始时间/安装时间，作为计算博客运行时间的参照值，请严格按照示例格式填写，否则将导致报错

    - group: style
      label: 主题设置
      formSchema:
        - $formkit: color
          name: theme_color
          label: 主题颜色
          value: '#49b1f5'
          placeholder: 请填写主题颜色
          help: '主题颜色运用到大部分模块色调，默认 #49b1f5'
          validation: required
        - $formkit: text
          name: content_max_width
          label: 内容区最大宽度
          value: 1350
          placeholder: 请填写内容区最大宽度
          help: 内容区域最大宽度，像素或百分比，默认 1350px
          validation: required|number

    - group: nav
      label: 导航设置
      formSchema:
        - $formkit: text
          name: nav_default_font_color
          label: 浅色导航默认背景颜色
          value: '#eee'
          placeholder: 请填写导航默认背景
          help: '导航默认背景 默认值 #eee' 

