apiVersion: 2.0
kind: Setting
metadata:
  name: theme-default-setting
spec:
  forms:
    - group: base
      label: 基本设置
      formSchema:
        - $formkit: select
          name: content_size
          label: 字体大小
          value: prose-base
          options:
            - value: prose-base
              label: prose-base
      
    - group: style
      label: 主题设置
      formSchema:
        - $formkit: text
          name: content_max_width
          label: 内容区最大宽度
          value: 1200
          placeholder: 请输入内容区最大宽度
          validation: required|number

